CREATE TABLE [dbo].[RoomType](
	[ID] [int] NOT NULL,
	[RoomType] [nvarchar](100) NULL,
 [Description] NVARCHAR(300) NULL, 
    CONSTRAINT [PK_RoomType] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
