CREATE TABLE [dbo].[RoomType](
	[RoomTypeId] [int] NOT NULL,
	[RoomType] [nvarchar](100) NULL,
    [Description] NVARCHAR(300) NULL, 
    CONSTRAINT [PK_RoomTypeId] PRIMARY KEY CLUSTERED 
(
	[RoomTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
